import { useMutation } from "@tanstack/react-query";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { api } from "~/utils/api";

const CreateLinkForm = () => {
  const [linkValue, setLinkValue] = useState("");

  const mutation = api.links.create.useMutation();
  const createLink = () => mutation.mutate({ points_to: linkValue });

  return (
    <>
      <input
        className="rounded-xl bg-white/10 p-4 text-white"
        type="text"
        placeholder="Link"
        value={linkValue}
        onChange={(e) => setLinkValue(e.target.value)}
      ></input>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
        <button
          className="flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
          onClick={createLink}
          disabled={mutation.isLoading}
        >
          Create
        </button>
        {mutation.isLoading && <p className="text-white">Loading...</p>}
        {mutation.isError && (
          <p className="text-red-500">Error: {mutation.error.message}</p>
        )}
        {mutation.isSuccess && (
          <p className="text-green-500">Success: {mutation.data?.link_id}</p>
        )}
      </div>
    </>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Linkaroo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Link<span className="text-[hsl(280,100%,70%)]">aroo</span>
          </h1>
          <CreateLinkForm />
        </div>
      </main>
    </>
  );
};

export default Home;
